Add support for root module samples
IgniteUI/igniteui-live-editing pull request #33
Opened 2023-01-24 15:23 UTC by dobromirts

Related to #https://github.com/IgniteUI/igniteui-angular-samples/issues/3239

2023-01-26 15:39 UTC, Svetloslav15 approved these changes

2023-01-27 13:26 UTC, hanastasov requested changes

2023-01-27 13:26 UTC, hanastasov commented on src/generators/SampleAssetsGenerator.ts
> +            if (sampleRoute.length > 4 && sampleRoute.substring(0, 4).localeCompare(ROOT_MODULE_PATH) === 0){
You know how to refactor it to look better 😎

2023-01-27 13:59 UTC, hanastasov approved these changes

2023-01-27 13:59 UTC, merged